package com.example.furnitures.entity;


// Planning to reduce this table

import java.util.List;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "Feasibilitys")
public class Feasibility {

	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	private int feasibilityId;
	
	private List<GeneratedImages> generatedImages;
	
	private Merchant merchant;
	
	private String status;
	
	private String comments;
	
	// If feasibility rejection count gets higher than 5 then user gets notified that the generated image is been rejected 
	// and the reject images generated by the particular customer will get deleted.
	
}
